import type { Metadata } from "next";
//import localFont from "next/font/local";
import "./globals.css";
import Header from './ui/header'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "fotio-alpha",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
  }) {
  
  return (
    <>
      {/* <Authenticator> */}
      <html lang='en'
               className={`h-full scroll-smooth antialiased`}>
       
         <body className='flex h-full flex-col text-stone-700'>
              
              <Header/>
                {children}
              {/* <Footer/> */}
            
        </body>
        
        </html>
        {/* </Authenticator> */}
    
   </>   
  )
}